import './global.css';
import { ThemeProvider } from '@nx-w/providers';
import { THEMES } from '@nx-w/config-ui';

export const metadata = {
  title: 'Welcome to javamas',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <ThemeProvider value={THEMES.javamas}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
